language: python

python:
  - 3.6

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements-ci.txt

script:
  # because we need to know what
  # is flake8 detecting bad faster and easier.
  - flake8 --show-source
  - python3.6 setup.py install
  - pytest
  - python3.6 upload.py
notifications:
  email: false
